name: torch
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch
  - pytorch-cuda=11.7
  - torchvision
  - torchaudio
  - jupyter
  - tqdm
  - matplotlib
  - scikit-learn
  - numpy
  - seaborn
  - flask
